### ISSUE TITLE
Exception with latest release

### ISSUE THREAD

**Issue by WeihanLi** [mingyaulee/Blazor.BrowserExtension#10]
When I referenced the latest release `0.2.0`, it seemed it would fail to build, the error is like follows:

![image](https://user-images.githubusercontent.com/7604648/120806444-6e77ed00-c579-11eb-9760-992999737cf1.png)

I had to change the code like below to build the project, wondering if this expected by design?

``` c#
await WebExtension.Tabs.Create(new WebExtension.Net.Tabs.CreateProperties
{
    Url = extensionUrl
});
```

**Comment by mingyaulee** [comment]
Hi Weihan, this is a breaking change as per the release notes. As this package is still in pre-release stage, the versioning is not according to semantic versioning yet. Breaking changes will be reflected in the minor version for now. You can view the changes [here](https://github.com/mingyaulee/Blazor.BrowserExtension/releases/tag/v0.2.0).

**Comment by WeihanLi** [comment]
Got it, thanks for your reply @mingyaulee
