### ISSUE TITLE
[BUG] it left _content folder by using dotnet publish command when reference to Razor class lib

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#11]
1. init a project
2. Add [AntDesign](https://www.nuget.org/packages/AntDesign/)
3. dotnet publish . -c Release -o out
4. out as below
![image](https://user-images.githubusercontent.com/7685462/120910251-f3fdb900-c6af-11eb-9ae7-1d6d8fd59e86.png)

**Comment by mingyaulee** [comment]
Fixed in release v0.3.3
