### ISSUE TITLE
Not able to read local file in WASM .NET Core layer

### ISSUE THREAD

**Issue by geetamshukla** [mingyaulee/Blazor.BrowserExtension#126]
I have developed a chrome extension using WASM and able to set bidirectional communication meaning I am able to call .NET Core function from JavaScript lib and JavaScript functions from WASM Dlls .

Now , I have a file URL which I want to download and then read the content in .NET Core layer . I have tried multiple ways but unable to achieve it in Blazor.BrowserExtension .

I am able to download a file in user's download folder and want to read the file from there not sure how we can achieve it as whatever file location I hardcode and pass it to WASM Dlls it always gives null as location .

@mingyaulee can u suggest a way by which we can read a file from file system ?

**Comment by mingyaulee** [comment]
Closed due to inactivity
