### ISSUE TITLE
Need help /suggestion to deploy chrome extension using WASM in ChromeOS

### ISSUE THREAD

**Issue by geetamshukla** [mingyaulee/Blazor.BrowserExtension#127]
I have developed a Chrome extension using WASM and I need to help /suggestion to deploy chrome extension using WASM in ChromeOS . I have developed Business logic using .NET Core 8 . 

Can you please let me know if there is any documentation available for the deployment  of Chrome extension using WASM in ChromeOS.

 I see that we can load the unpacked version of extension but not sure how the WASL dll will be executed .

**Comment by mingyaulee** [comment]
I suppose the publishing of extension should be the same for Chrome browser and Chrome OS. The WASM extension can be packed just like a regular JS extension.

This [page](https://developer.chrome.com/docs/webstore/publish) has a detailed guide on how to publish an extension to the store. 

There is also a tip from issue #39 

> Google on the other hand will reject your extension at first if you declare any chromium apis in the manifest. Their automated testing doesn't work with Blazor / WASM. Their support has managed to get it straightened out each time, but it's still frustrating.
