### ISSUE TITLE
Options page not exposed by Firefox

### ISSUE THREAD

**Issue by pm64** [mingyaulee/Blazor.BrowserExtension#14]
It should be noted that the following is required to appear in the manifest in order for Firefox to expose the options page:

  "options_ui": {
    "page": "index.html?path=options",
    "browser_style": true
  },

**Comment by mingyaulee** [comment]
Thank you for this. I'll update the readme to use this instead since Firefox has deprecated the use of `options_page`.

**Comment by mingyaulee** [comment]
Resolved in v0.3.7
