### ISSUE TITLE
blazor.webassembly.js 404 when running from VS or Rider

### ISSUE THREAD

**Issue by Simcon** [mingyaulee/Blazor.BrowserExtension#145]
When creating an empty project, the blazor.webassembly.js fails to load when started from VS or Rider, causing the load to fail.

Other files from _framework seem to load okay.

![image](https://github.com/mingyaulee/Blazor.BrowserExtension/assets/1893351/6415508d-a99d-4b41-af14-bb966faeff8b)

**Comment by mingyaulee** [comment]
Thank you for reporting this! It should be fixed now in v1.4.1. Please reopen the issue if you still encounter it.

**Comment by Simcon** [comment]
Confirmed working - thanks!
