### ISSUE TITLE
manifest.json template (v0.3.8)

### ISSUE THREAD

**Issue by vsauvage-ciis** [mingyaulee/Blazor.BrowserExtension#15]
Hi, 

The template manifest.json file included in nuget package Blazor.BrowserExtension.Build has a typo:

  "web_accessible_resources": [
    "framework/*",
    "BrowserExtensionScripts/*",
    "WebExtensionScripts/*"
  ],

This block does not pass the build check for "WebExtensionsScripts/*" and raises the following build error:
Manifest item 'web_accessible_resources' must specify "framework/*", "BrowserExtensionScripts/*" and "WebExtensionsScripts/*".	

There is a missing "s" in WebExtensionScripts, expected WebExtensionsScripts

Kind regards.

**Comment by mingyaulee** [comment]
You are absolutely right! I'll push a fix for it today.

**Comment by mingyaulee** [comment]
Fixed in v0.4.0
