### ISSUE TITLE
Build fails with version 1.5.0

### ISSUE THREAD

**Issue by Telavian** [mingyaulee/Blazor.BrowserExtension#150]
If I do a `dotnet build` for versions earlier than 1.5.0 then it works. However 1.5.0 fails with the following error:

`...\.nuget\packages\blazor.browserextension.build\1.5.0\build\Blazor.BrowserExtension.Build.Build.targets(87,5): error MSB3030: Could not copy the file "...\obj\Debug\net8.0\browserextension\build\BackgroundWorker.js" because it was not found.`

**Comment by Telavian** [comment]
It probably has to do with BackgroundWorker.js now being auto generated. I had the actual js file not the CS file it was generated from.

**Comment by mingyaulee** [comment]
Thanks for reporting this. You can downgrade to v1.4.2 for now and I'll get it fixed soonest possible.

**Comment by bv5396** [comment]
> Thanks for reporting this. You can downgrade to v1.4.2 for now and I'll get it fixed soonest possible.

how to downgrade?

**Comment by mingyaulee** [comment]
This has been resolved in `v1.5.1`.
