### ISSUE TITLE
 build error:Manifest item 'background' must specify "index.html?path=background" as background page 

### ISSUE THREAD

**Issue by git-Charlie** [mingyaulee/Blazor.BrowserExtension#16]
`\Debug\net5.0\wwwroot\manifest.json(6-6): error : Manifest item 'background' must specify "index.html?path=background" as background page `

**Comment by mingyaulee** [comment]
Thanks for reporting this, I must have missed updating the package reference in the template to the latest version. Can you please try to update the package reference version in the csproj from `v0.4.*` to `v0.5.*`?
