### ISSUE TITLE
Background worker crashes on Firefox

### ISSUE THREAD

**Issue by KanTheAstronaut** [mingyaulee/Blazor.BrowserExtension#168]
Hello!

I want to start by saying that this library has been a life saver when it comes to using Blazor to create a web extension!

I've recently been encountering an issue once I started using the background worker in my code and realized that it never actually runs on firefox due to an error while it is starting up.

The error that shows up in the extensions console is this:
`Uncaught TypeError: setting getter-only property "window"
    <anonymous> moz-extension://....../content/Blazor.BrowserExtension/BackgroundWorkerRunner.js:178
BackgroundWorkerRunner.js:178:33
`

I've also tried the "Messaging" sample from https://github.com/mingyaulee/Blazor.BrowserExtension.Samples but that also leads to the same issue i encountered when working on my own project.

I just want to mention that this issue does not show up on chrome everything works perfectly fine when the sample is run there. I've only encountered the error with firefox (it may be present in other browsers too but i haven't tested anything else)

---
#### Steps to reproduce:
- Load up the Messaging sample on firefox
- Click on inspect and the error will be there

**Comment by mingyaulee** [comment]
Hello, thank you for the feedback and for trying out the sample project too. Indeed the background worker is a new feature and was not working in Firefox. I have released a new version `v1.5.3` which includes the fix for this.

**Comment by KanTheAstronaut** [comment]
Hello

`v1.5.3` fixes the issue for firefox but introduces a new error for chrome because at line 37 in [BackgroundWorkerRunner.js](https://github.com/mingyaulee/Blazor.BrowserExtension/blob/334e948553842c095fe5684f045557a1cc4a590c/src/Blazor.BrowserExtension/content/src/BackgroundWorkerRunner.js#L37) it tries to access `elements` but because of how it's defined it's out of scope.

I can make a pull request in a bit with what I've done to fix it on my end
