### ISSUE TITLE
Clarification Needed on Using Func with ScriptInjection

### ISSUE THREAD

**Issue by bogdaniolu97** [mingyaulee/Blazor.BrowserExtension#178]
I’ve encountered difficulties using the Func property from ScriptInjection and haven’t been able to get it working. Any guidance or examples would be greatly appreciated.

` string InjectScriptAction()
{
    return "function colorRed2(){console.log(\"colorRed3\"); document.body.style.backgroundColor = 'red'; }";
}
var scriptInjection = new ScriptInjection

{
    Target = new InjectionTarget

    {
        TabId = tab.Id.Value,
    },
    Args = new List<object>() { "firstArgument" },
    Func = () => InjectScriptAction(),

};
var result = await WebExtensions.Scripting.ExecuteScript(scriptInjection);`

manifest.json:
{
  "manifest_version": 3,
  "name": "Browser Extension With Blazor Extension",
  "description": "My browser extension built with Blazor WebAssembly",
  "version": "0.1",
  "permissions": [
    "activeTab",
    "tabs",
    "storage",
    "webRequest",
    "bookmarks",
    "cookies",
    "downloads",
    "notifications",
    "webNavigation",
    "contextMenus",
    "scripting"
  ],
  "optional_permissions": [
    "topSites"
  ],
  "optional_host_permissions": [
    "https://*/*",
    "http://*/*"
  ],
  "host_permissions": [
    "http://*/*",
    "https://*/*"
  ],
  "background": {
    "service_worker": "content/BackgroundWorker.js",
    "type": "module"
  },
  "action": {
    "default_popup": "popup.html"
  },
  "options_ui": {
    "page": "options.html",
    "open_in_tab": true
  },
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval'; object-src 'self'"
  },
  "content_scripts": [
    {
      "matches": ["<all_urls>"]
    }
  ],
  "web_accessible_resources": [
    {
      "resources": [
        "framework/*",
        "content/*",
        "js/*.js"
      ],
      "matches": [ "<all_urls>" ]
    }
  ]
}

**Comment by mingyaulee** [comment]
The script injection feature might not be suitable to be executed from dotnet because dotnet is not available in the injected window. I haven't tested it personally yet, but it looks like it would be better to separate the injection into another JS file and use the Files property to inject the scripts.

**Comment by mingyaulee** [comment]
Also, evaluating JS in string is completely blocked by manifest v3, so your code that returns JS string will just be a string and will not be executed.

**Comment by mingyaulee** [comment]
Closed due to inactivity
