### ISSUE TITLE
Migrate to manifest V3

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#18]
In the Chrome extension store, there is a notice that "Simply migrate to Manifest V3 and enjoy faster auditing services and new APIs and features."

details: https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by mingyaulee** [comment]
You can absolutely implement manifest v3 for your extension, currently there is a validation of the manifest version in the build process but it will be removed soon. One thing to be aware of is that
- it is not a standard across browsers ([standardisation is underway](https://github.com/w3c/webextensions))
- the APIs may differ in different browsers ([Firefox's implementation is still under development](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/))
- the browser polyfill does not support the new APIs yet ([issue](https://github.com/mozilla/webextension-polyfill/issues/329#issuecomment-881372516))

**Comment by newbe36524** [comment]
It is nice of you to reply to my question, I think there is nothing needs to be done by this framework but left a link in README.md to indicate this issue.
You can close this as you wish.

**Comment by mingyaulee** [comment]
Yeah absolutely, I will add a section in the readme for manifest v3.

**Comment by newbe36524** [comment]
it is about to end of life about manifest v2 https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

**Comment by mingyaulee** [comment]
Yes, unfortunately there is still a lot of work that needs to be done before Blazor can be used in MV3 extensions.

At least 2 issues in Chromium that I am aware of:
- [Support loading wasm in extensions manifest v3](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354)
- [implement extension service worker](https://bugs.chromium.org/p/chromium/issues/detail?id=1198822)

Standardization of web extensions are still underway and it will take some time to get implemented in all the browsers.
