### ISSUE TITLE
Not able to fetch the content from PPT file in WASM as well as Javascript files.

### ISSUE THREAD

**Issue by bharathtl18369011** [mingyaulee/Blazor.BrowserExtension#180]
I have chrome extension for validating emails in GMail. But unfortunately, no dll supported in WASM or Javascript  for PPT (I can use Aspose.slides for pptx). Need your input.

**Comment by mingyaulee** [comment]
I believe what you are looking for is [OpenXML SDK](https://github.com/dotnet/Open-XML-SDK) which is maintained by Microsoft.

There is a sample usage for PPT in https://github.com/dotnet/Open-XML-SDK/blob/main/samples/PowerPointModernCommentSample/Program.cs
