### ISSUE TITLE
BackgroundWorker.js not defined from template 

### ISSUE THREAD

**Issue by bradleyables22** [mingyaulee/Blazor.BrowserExtension#184]
I downloaded the most recent version of the template and on initial build I am seeing this error.

The "ApplyCompressionNegotiation" task failed unexpectedly. System.InvalidOperationException: Fingerprint for 'D:\Toppik\Toppik_Browser_Extension\obj\Debug\net8.0\browserextension\build\BackgroundWorker.js' is not defined. at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate() at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item) at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext() at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute() at Microsoft.Build.BackEnd.TaskExecutionHost.Execute() at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by mingyaulee** [comment]
There is an existing issue #179, .Net is not officially supported by this package yet. Workaround is to use .Net 8 SDK with global.json
