### ISSUE TITLE
Failed to publish to Firefox with some lint error

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#20]
Error: There is a JavaScript syntax error in your code, which might be related to some experimental JavaScript features that aren't an official part of the language specification and therefore not supported yet. The validation cannot continue on this file.

It is verified by https://github.com/mozilla/addons-linter/ lint when you want to publish extension 
 
![image](https://user-images.githubusercontent.com/7685462/130395078-4e55cc99-4dc9-49df-b99c-9005898a639d.png)

**Comment by mingyaulee** [comment]
I see from the issues in the Mozilla linter project that [modules are not supported yet](https://github.com/mozilla/addons-linter/issues/3842). I do have plans to concatenate the scripts and not use modules so it seems I have to bring forward this plan.

**Comment by newbe36524** [comment]
Thanks to your nice work, everything works well now.

**Comment by willdurand** [comment]
> I see from the issues in the Mozilla linter project that [modules are not supported yet](https://github.com/mozilla/addons-linter/issues/3842). I do have plans to concatenate the scripts and not use modules so it seems I have to bring forward this plan.

FWIW, the issue linked above is for internal addons-linter stuff, not for supported features in web extensions. I think modules are already supported by FF and the linter also allows to use modules.

**Comment by newbe36524** [comment]
But anyway, at the time, I actually received this error report when I was uploading the addons. It prevented me from making further submissions.
Currently, after I use the latest version of BlazorExtensions, these errors are gone.
I have now also successfully upload the addons.
https://addons.mozilla.org/zh-CN/firefox/addon/amazing-favorites/

Maybe there is a better way to fix the linter or this project, but I don`t know.
