### ISSUE TITLE
@page "/contentscript.html" is not working 

### ISSUE THREAD

**Issue by yuzd** [mingyaulee/Blazor.BrowserExtension#23]
```
@page "/contentscript.html"
@inherits BasePage

<h3>ContentScript</h3>

@code {

}
```

```csharp
 public partial class ContentScript
    {
    
        [Inject] public IJsRuntimeAdapter JsRuntimeAdapter { get; set; }

        protected override async Task OnInitializedAsync()
        {
            Console.WriteLine("dddd");
            
            await base.OnInitializedAsync();
        }
    }
```

dddd is not log in console

![image](https://user-images.githubusercontent.com/16083659/132236105-bdc02d72-b94d-425b-9bb8-b477a6edf87e.png)

**Comment by mingyaulee** [comment]
Have the `manifest.json` and `Program.cs`been updated accordingly?

**Comment by yuzd** [comment]
manifest.json

![image](https://user-images.githubusercontent.com/16083659/132264364-9e804903-0275-46ec-b290-3a177ed6cecd.png)

App.razor
![image](https://user-images.githubusercontent.com/16083659/132264371-a2cf5683-1dab-44de-8530-152d2f589038.png)

Program.cs
![image](https://user-images.githubusercontent.com/16083659/132264381-44512dcd-9067-486c-8eed-3f91f1518681.png)

**Comment by mingyaulee** [comment]
Just one last thing to check, perhaps the ContentScript in App.razor is not referring to the actual component. If you are using Visual Studio you can check easily by hovering the component, it should say `fishGo.Pages.ContentScript`.

You can try adding `@using fishGo.Pages` in the App.razor and see if the content scripts is rendered in the site you are expecting.

**Comment by yuzd** [comment]
you are right.
