### ISSUE TITLE
Fail to build in net6 rc1

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#25]
🤪
https://github.com/Amazing-Favorites/Amazing-Favorites/pull/153/checks?check_run_id=3606630901

**Comment by mingyaulee** [comment]
I looked at the changes in RC1 and the static web assets manifest have changed from XML to JSON. So just a heads up it's going to take some time to resolve this issue.

**Comment by newbe36524** [comment]
too many changed 👻

**Comment by mingyaulee** [comment]
I have added JSON manifest reader as well in v0.6.2 and tried out a simple project build with RC1. You can try it out and reopen this issue if it still doesn't work.

**Comment by newbe36524** [comment]
It can build w/o error but something wrong with Razor llibary e.g. AntDesignBlazor

It need to keep structure as source directory, but it left as target now as error folder structure as below:
<img width="923" alt="explorer_cWU2jGf8Mt" src="https://user-images.githubusercontent.com/7685462/133804432-f90ed2c4-91d4-4db5-8cec-022dbf0aca32.png">

Here is the json file at bin\Debug\net6.0\Newbe.BookmarkManager.staticwebassets.runtime.json  (rename to json if you download

[Newbe.BookmarkManager.staticwebassets.runtime.json.csv](https://github.com/mingyaulee/Blazor.BrowserExtension/files/7186596/Newbe.BookmarkManager.staticwebassets.runtime.json.csv)

**Comment by mingyaulee** [comment]
Thanks for the JSON file, I'll take a look at it

**Comment by mingyaulee** [comment]
I have pushed a fix for the directory structure in v0.6.3

**Comment by newbe36524** [comment]
thanks for your awesome work. it works well now!
