### ISSUE TITLE
Is it possible to implement a custom request copy browser extension

### ISSUE THREAD

**Issue by WeihanLi** [mingyaulee/Blazor.BrowserExtension#27]
I wanna copy the request as a custom request, but not sure if a web browser extension could help, and is there some guide for this?

![image](https://user-images.githubusercontent.com/7604648/133864766-3c6d2e20-1318-4e7e-9605-4409459a9f11.png)

**Comment by mingyaulee** [comment]
The best bet is to explore the APIs under DevTools namespace. As far as I know (which is not much), there is none that can have a custom context menu in the original DevTools Network panel. Perhaps it is possible to create a custom "Network" panel with your own view page. This [link](https://developer.chrome.com/docs/extensions/mv3/devtools/) may help you get started. You can use ["devtools.network" API](https://developer.chrome.com/docs/extensions/reference/devtools_network/) to get the requests.

**Comment by WeihanLi** [comment]
@mingyaulee  thanks for your reply, I did some research on Chrome API documents but had found any document or sample add a new item on the Network pannel

> Perhaps it is possible to create a custom "Network" panel with your own view page. 

Great idea, thanks for your help

**Comment by yuzd** [comment]
@WeihanLi 用插件的方式如何扩展这个 你搞定了？

**Comment by WeihanLi** [comment]
@yuzd 还没做，想直接在 Network Panel 上扩展应该不行，没有找到有 API 支持，应该要像 @mingyaulee 说的那样尝试自己创建一个类似于 network 的 panel 来实现
