### ISSUE TITLE
Debugging while running as extension

### ISSUE THREAD

**Issue by garethhayter** [mingyaulee/Blazor.BrowserExtension#34]
I know you say there is no way to debug while running as an extension, but is there any way to write to the Chrome dev tools console, or even write alerts? I just want to somehow get some idea of what's happening.

I'm a newbie to Chrome extensions (and Blazor) so apologies if I'm asking a really stupid question!

**Comment by mingyaulee** [comment]
It's completely alright to ask questions here, no worries. You can definitely write logs or messages or even objects to the console by using `System.Console.WriteLine`. In Blazor it automatically writes to the JavaScript console so you can view it from the developer tools, just like when you are developing using any other front end frameworks.

**Comment by garethhayter** [comment]
Thank-you, that works perfectly. Is there any documentation regarding interacting with WebExtensions.Net? I want to subscribe to events when the URL changes. I assume that I should be using WebExtensions.Tabs.OnUpdatedEvent? What's the best-practice place for global event listeners like this? Also, I've tried something like this, but it's obviously not working:

WebExtensions.Tabs.OnUpdatedEvent((x, y, z) =>
     System.Console.WriteLine("URL changed")
);

Any pointers would be very welcome, thank-you!

**Comment by mingyaulee** [comment]
The comprehensive documentations for the APIs are available from both Chrome and MDN, for example [chrome.tabs#onUpdated](https://developer.chrome.com/docs/extensions/reference/tabs/#event-onUpdated). The package WebExtensions.Net provides the JavaScript binding to interop to the actual API if it is available. 

Note that you will need to add the corresponding permission in the manifest first before the API can be consumed during runtime.
