### ISSUE TITLE
Question - Extension published featuring Blazor.BrowserExtension - Any specific information you'd like in the listing?

### ISSUE THREAD

**Issue by dragnilar** [mingyaulee/Blazor.BrowserExtension#35]
@mingyaulee  

I didn't see any other way to contact you with this question, so sorry if this isn't the best way to handle it. 

I was able to get approval from Microsoft and they published an extension I made using Blazor.BrowserExtension.  It's a simple extension that overrides the Edge new tab page with some additional features / differences.

Right now, I have a note about using Blazor.BrowserExtension on the github site but I forgot to note it on the marketplace listing. Do you want me to add anything about it there? I am not aware of there being any other extensions on the Edge site that make note of using Blazor. 

https://microsoftedge.microsoft.com/addons/detail/blazor-edge-new-tab/bfhdepjammnaoddhikhogfbnikmeocfj

**Comment by mingyaulee** [comment]
Hi, this is a completely fine way to contact me, and nice of you to ask about the topic. You are free to distribute the extensions without mentioning this project.

Btw, congratulations on publishing your extension. If I may, I would like to add your project link to the samples readme file for others to have a reference as well.

**Comment by dragnilar** [comment]
@mingyaulee Ah ok, I wasn't sure about the latter. I still noted it on the github page since I think people should be aware of it. And thanks for the congrats, I appreciate it. Please feel free to add it to the readme. 👍

**Comment by mingyaulee** [comment]
Alright cool!
