### ISSUE TITLE
Build failed from 0.7.3 to 0.8.1

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#36]
refer to https://github.com/Amazing-Favorites/Amazing-Favorites/pull/221
log details https://github.com/Amazing-Favorites/Amazing-Favorites/runs/4493557911?check_suite_focus=true

**Comment by mingyaulee** [comment]
This has been fixed in v0.8.2

**Comment by newbe36524** [comment]
awsome！
