### ISSUE TITLE
How to intercept webRequest events

### ISSUE THREAD

**Issue by garethhayter** [mingyaulee/Blazor.BrowserExtension#37]
How can webRequest events be intercepted? (eg: onSendHeaders, onComplete, onAuthRequired) Apart from declaring the correct permissions in the manifest file, where should the code be placed and how should it be hooked up?

Docs: https://developer.chrome.com/docs/extensions/reference/webRequest/

**Comment by mingyaulee** [comment]
You can find an example usage of the blocking `webRequest` API in the background page. This helps to support the virtual path routing.

https://github.com/mingyaulee/Blazor.BrowserExtension/blob/d8b0d5cdbac8cf58faa584726f0949d8505989a6/src/Blazor.BrowserExtension/Pages/BackgroundPage.cs#L32-L41
