### ISSUE TITLE
Quick Note on publishing extensions to the Chrome Store - probably should be added to the readme

### ISSUE THREAD

**Issue by dragnilar** [mingyaulee/Blazor.BrowserExtension#39]
@mingyaulee 

I was able to get my extension added to the [Chrome Web Store](https://chrome.google.com/webstore/detail/blazor-edge-new-tab/bdcfngldhocoffghnlmhibpifmoakiec?hl=en&authuser=0) (in addition to the Edge store).

A couple of things to note about this:

- Microsoft is far easier to deal with as long as you note somewhere in the testing steps and/or description that the extension uses Blazor. It's slower than Google but it's pretty much a hassle free experience.

- Google on the other hand will reject your extension at first if you declare any chromium apis in the manifest. Their automated testing doesn't work with Blazor / WASM. Their support has managed to get it straightened out each time, but it's still frustrating. 

Needless to say, you may want to note in the read me that developers should expect some difficulty with Google if they wish to publish a Blazor extension to the Chrome store. 

The last correspondence I had with Google's support said that they are discussing how to make the submission of WASM extensions easier. So hopefully this isn't a permanent problem.

**Comment by mingyaulee** [comment]
Thank you for sharing your experience. I completely agree that it should be mentioned in the readme for others to be aware of as well. Wasm extensions still need to be improved especially in manifest v3 since there has been many complaints about it.

**Comment by mingyaulee** [comment]
I have added the notes to the readme. Just a quick question though, I saw that in the chrome store it says the extension is about 22MB, do you have any large dependencies? This is because I checked the publish size in the samples project it is only less than 5MB.

**Comment by dragnilar** [comment]
@mingyaulee  

Thanks for bringing that up, it was largely because I was just sending them the release folder. I did try publishing it just now to see if that makes a difference and it trimmed it down to 11 mb (most of it was coming from the framework folder). I probably could shave it down more by doing some things to bootstrap but I'd rather get a couple of things ironed out in the extension first.

One thing about publishing I've found is that it doesn't rename the _content and _framework folders automatically in Visual Studio. Loading the extension unpacked gives you the usual error saying you can't have underscores in file names. Work around for this is to update all references of _framework in blazor.webassembly.js with framework. 

Loading it packed gives me an error from core.js. 

Maybe I overlooked something in the documentation?

**Comment by mingyaulee** [comment]
Build and publish should both rename the folders _framework and _content. Are you loading the unpacked extension from the browserextension folder instead of the wwwroot folder?

**Comment by dragnilar** [comment]
Build renames the _content and _framework folders as expected inside of the bin\buildtype\net6.0\browserextension folder.

Publish creates a bin\Release\net6.0\browser-wasm\publish\wwwroot folder with a web.config file outside of it. This is using the publish wizard in VS. Unless I am missing something, I would presume that wwwroot folder is supposed to be the published browser extension?  Should I be using dotnet publish instead?

**Comment by mingyaulee** [comment]
Oh yes you should use the command `dotnet publish -c Release` instead because the VS publish wizard does not invoke the msbuild target provided by this package.
