### ISSUE TITLE
Manifest version 2 project are no longer supported on Google Chrome store

### ISSUE THREAD

**Issue by miniatarule** [mingyaulee/Blazor.BrowserExtension#41]
HI! 

Manifest version 2 projects are no longer supported on Google Chrome store.
I just tried to submit a Blazor extension with manifest version 2 and I couldn't. Now Google required that all extensions manifest version 3 only.

Are you planning to update the manifest to version 3?

**Comment by mingyaulee** [comment]
Hi! I am aware of the deprecation of manifest V2 in chrome store. I do plan to add support for manifest V3 as soon as I can. There were a couple of issues earlier preventing from loading wasm in an extension, I will look into it again soon to see if we can start migrating to manifest V3.

**Comment by mingyaulee** [comment]
I will use this issue to track the progress of migrating to manifest v3.

Blockers:
1. [Wasm cannot be loaded in manifest v3](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354)
    - Potential workaround 1: compile to single JS file with DotNetJs - requires 'unsafe-eval' which is not allowed in manifest v3
2. [Dynamic import is not allowed in service workers](https://bugs.chromium.org/p/chromium/issues/detail?id=1198822)
    - Potential workaround 1: use static import - results in longer load but initialization will be stuck at 1st blocker.

**Comment by mingyaulee** [comment]
Update:
Bug [Wasm cannot be loaded in manifest v3](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354) is fixed and will likely be released in Chrome version 102.

**Comment by mingyaulee** [comment]
Tested with Chrome Dev channel, manifest v3 can be loaded but Blazor cannot be initialized due to the requirement of 'unsafe-eval' CSP in dotnet runtime, which is resolved and targeted to be released in .Net 7.
Source: [Make mono CSP Compliant](https://github.com/dotnet/runtime/issues/59416)

**Comment by mingyaulee** [comment]
Update:

Blockers:
1. ~~[Wasm cannot be loaded in manifest v3](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354)~~
    - Fixed in Chrome 102, tested in Chrome Dev channel
2. [Dynamic import is not allowed in service workers](https://bugs.chromium.org/p/chromium/issues/detail?id=1198822)
    - Workaround: use static import
    - Impact: results in slightly longer load time
3. [DotNet runtime requires unsafe eval in CSP which is not allowed in MV3](https://github.com/dotnet/runtime/issues/59416)
    - No workaround
4. [Blazor requires unsafe eval in CSP which is not allowed in MV3](https://github.com/dotnet/aspnetcore/issues/37787)
    - No workaround

**Comment by gitlsl** [comment]
是否可以理解 当 ,net7 正式版发布的时候， 上述问题就全都被解决了吗可以支持MV3了？

**Comment by mingyaulee** [comment]
@gitlsl .Net 7和Blazor还没有解决CSP的问题。一旦解决了还需要再测试能否用MV3来启动Blazor。

**Comment by gitlsl** [comment]
@mingyaulee 似乎已经解决了

**Comment by davidchavezgrant** [comment]
Has anyone been able to get this running using manifest v3?

**Comment by mingyaulee** [comment]
The issue in [dotnet/runtime#68374](https://github.com/dotnet/runtime/issues/68374) is still open. Dotnet runtime still requires `unsafe-eval` CSP directive which is not allowed in MV3.

**Comment by mingyaulee** [comment]
Good news! Manifest V3 is now supported, with .Net 7 RC1 released.

Please read on this in the project README, migration guide is provided.

Any problem should be reported as new issue. This issue will be closed now.

> Note: The `dotnet.js` runtime in .Net 7 is still not CSP compliant. We are now using a custom build of `dotnet.js` runtime which is built from the source code with modifications to make it CSP compliant, this will be used until .Net 8 is released.
