### ISSUE TITLE
Extension created with your project cannot get loaded in chrome

### ISSUE THREAD

**Issue by miniatarule** [mingyaulee/Blazor.BrowserExtension#42]
When I try to load the extension I get this error:  

Cannot load extension with file or directory name _framework. Filenames starting with "_" are reserved for use by the system.
Could not load manifest

**Comment by mingyaulee** [comment]
Are you able to share a minimum reproducible sample project?

**Comment by miniatarule** [comment]
the _framework  ==> the underscore in the folder name cause an error. Underscore cannot be used in chrome extension folder name.

Just create a sample project and try to load it in chrome as an extension and you will see the error.

**Comment by mingyaulee** [comment]
The folder should be renamed during the build, you will then be able to load the extension from the browser. If you are trying to load from the `wwwroot` folder it will not work though. It should be loaded from the `browserextension` folder.
