### ISSUE TITLE
_content renaming missed for RCL

### ISSUE THREAD

**Issue by gerneio** [mingyaulee/Blazor.BrowserExtension#43]
I've noticed that if I pull in a Razor Class Library, the import line in the output "$(ProjectName).styles.css" does not have the "_content" replaced, similar to other files. For now, I created a "PostBuildEvent" with a dependency on "RunBuildBlazorToBrowserExtension" to manually replace that one word, and now the app displays and behaves correctly. I "think" the issue is part of "Blazor.BrowserExtension.Build.Tasks.BlazorToBrowserExtensionProcessStaticWebAssetsManifest" but not 100% sure (didn't evaluate any code). I'm still new to Blazor and the latest AspCore (let alone browser extension), so I could have misunderstood some things, but hopefully, this gets you to the right place.

![image](https://user-images.githubusercontent.com/13949170/158277869-22b6e42d-2aa6-431a-8ef1-8337bac7b17e.png)

Btw, this is a really awesome project you've got here! It was ridiculously easy to get up and going, even though I'm still fairly new to all three of these technologies (Blazor, AspCore, & browser extensions). The only suggestion I would have is tailoring the samples & templates to be closer to the look and feel of the default Blazor templates, but I was able to get over the hump relatively quickly.

P.S. Looking forward to Chrome getting the WASM issues resolved so that we can use MV3 since MV2 will be dead in the water soon.

Thanks!

**Comment by mingyaulee** [comment]
Glad you like the project. You are right, it is somewhere in the Blazor.BrowserExtension.Build.Tasks, not the one you mentioned but very close. Currently for RCL the build is only renaming the output folder structures without touching the RCL assets. I will add this into the build targets as well to make sure the output contents use the right path for import.

**Comment by gerneio** [comment]
It's one of my own making, which is essentially just the combination of the RCL template and basic Blazor template. I'll post it tomorrow if you still need it.

**Comment by mingyaulee** [comment]
In that case, maybe you can change the import to use relative path instead, e.g. `../another folder/file.css` or `subfolder/file.css`.

This is because the workaround I can think of feels messy to implement and I would prefer not to go down that direction if it is possible.

**Comment by gerneio** [comment]
I'm not sure i understand, where and what would I be changing?

**Comment by mingyaulee** [comment]
Hi @gerneio, have you made progress with the RCL? Is this still an issue?

**Comment by gerneio** [comment]
I haven't messed with it anymore since I already had a quick fix in place.

**Comment by mingyaulee** [comment]
I have decided to not produce any fix for this because the fix will either be
1. impacting other projects consuming the same RCL package (replace content in package), or
2. too complicated (copy file, replace contents and update static assets manifest)

It is easier to fix this from the RCL package, where relative import path should be used.

Avoid: `/_content/package/css/x.css`
Use: `x.css`
Use: `css/x.css`
Use: `./x.css`
Use: `../css/x.css`
Use: `../../package/css/x.css`

**Comment by datvm** [comment]
@mingyaulee hi since this is marked as `wontfix` I wonder if you can reconsider it. There are many Blazor library that the author use dynamic import (with hardcoded string with `_content`) instead and we usually do not have easy access to modifying it.

**Comment by mingyaulee** [comment]
@datvm the contents from RCL has two types, CSS and JS. As far as I know, the CSS is automatically loaded but the JS needs to be imported manually, either by consuming project or the package. 
1. The consuming project can add a `script` tag in the html.
2. The package can import dynamically from wasm.

**Comment by datvm** [comment]
For RCL that uses option 2, I wrote https://github.com/datvm/Blazor.JsRuntimeRedirect to solve the problem. The library override `IJsRuntime` to manually update the `_content` path. Useful for anyone who needs it in the future.

**Comment by mingyaulee** [comment]
@datvm the solution that you have implemented intercepts dynamic imports from C#, which works in most cases up to .Net 7. A new interop [JSImport](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0) has been introduced and RCL packages may be moving to use that, then the solution you have implemented will not work anymore. In my opinion, the projects that published the RCL package should be fixing it from their side using [JavaScript initializers](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#javascript-initializers-1) for a longer term solution.

**Comment by datvm** [comment]
Thank you I am not aware of either of these! I am going to look into it and see if I can fix `JSImport`. JS initializers look good and I hope developers would move onto it. Do you know if it works out of the box for Chrome Extension?

**Comment by mingyaulee** [comment]
It will work because this package replaces the path in blazor.boot.json where the library initializers are defined.
