### ISSUE TITLE
Unable to open popup. file not found error

### ISSUE THREAD

**Issue by zubairkhakwani** [mingyaulee/Blazor.BrowserExtension#44]
I am trying to create an extension when i create a new project using tempalte and upload to chrome extension after publishing it shows this page 
![image](https://user-images.githubusercontent.com/38009549/190962807-12a0234c-96b3-4586-ab8b-055876dc2f08.png)
i am trying this from tomorrow but unable to make it work.

i am using manifest v3 and dotnet 7 preview version, In dotnet 6 project it's loading assemblies from framework folder but in dotnet 7 it's trying to load from _framework folder. 

can you please upload a working example of extension with popup page. Thanks

**Comment by mingyaulee** [comment]
I have just tried with the latest version of template, it works fine. Are you using the latest .Net 7 rc1 SDK? If yes, are you able to share a reproducible project with the build output?
