### ISSUE TITLE
Ability to change the icon dynamically

### ISSUE THREAD

**Issue by jtourvieille** [mingyaulee/Blazor.BrowserExtension#45]
Hello,

First, thanks for this wonderful project.

I wonder if it is possible to dynamically change the top right icon based upon states.

For instance, let's say Condition A is met, then I want the icon to be red, if not, then the icon is Yellow.

![image](https://user-images.githubusercontent.com/2754206/192998936-41fd69c5-5866-4538-82d9-7c8a7f3dea04.png)

Thanks!

**Comment by mingyaulee** [comment]
Hello, thanks for the feedback!
Yes it is possible, check out the [`action` API](https://developer.chrome.com/docs/extensions/reference/action/) which has the `setIcon` and `setBadgeBackgroundColor` method for changing the appearance of the icon.

**Comment by jtourvieille** [comment]
Great, I'll have a look.

Thanks for the answer.
