### ISSUE TITLE
blazor.boot.json libraryInitializers incorrect path

### ISSUE THREAD

**Issue by johnW-ret** [mingyaulee/Blazor.BrowserExtension#46]
This is my first time submitting an issue on a public repository, so forgive my ignorance please 🙂.

Issue:
> Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: chrome-extension://[my-chrome-extension-id]/_content/Microsoft.Fast.Components.FluentUI/Microsoft.Fast.Components.FluentUI.lib.module.js
at
> content/Blazor.BrowserExtension/Core.js:43 (anonymous function)

I have referenced the above package in my project. In ...\net7.0\browserextension\framework\blazor.boot.json, When I change "_content" to "content" under "libraryInitializers", the extension loads as expected.

How to replicate:
`dotnet new browserext`
`dotnet add package Microsoft.Fast.Components.FluentUI`
`dotnet build`
then load unpacked into Microsoft Edge

I suspect this is similar to #43, but I do not understand the architecture of this project well enough to fix it myself without direction. Willing to fix and PR myself once I get a better understanding.

Thanks. Love this project, by the way!

**Comment by mingyaulee** [comment]
Thanks for reporting the issue! The fix is quite simple and has been implemented. You can update to the latest version v0.10.3 to get it.
