### ISSUE TITLE
Support to load razor class libary

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#5]
## Background

There are some useful razor class libary for developer to build razor application.
We need to support to load them in dev and production.

## Proposal

Here is an example of introducing [ant-design-blazor](https://github.com/ant-design-blazor/ant-design-blazor)

We would normally develop a blazor application using the dev server to help us start a web server during development. 
However, the chrome extension is loaded from a folder, so the dev server cannot be used.
This causes us to ignore the static files that are in the razor class libary.
Therefore, we should copy and parse them to the output directory.

After the project is successfully built, we can find the static file configuration xml in the project's obj/Debug/net5.0/staticwebassets, such as the following.

```xml
<StaticWebAssets Version="1.0">
  <ContentRoot BasePath="_content/AntDesign" Path="C:\Users\Administrator\.nuget\packages\antdesign\0.8.0\build\..\staticwebassets\" />
  <ContentRoot BasePath="/" Path="C:\Repos\newbe\Newbe.BookmarkManager\src\Newbe.BookmarkManager\bin\Debug\net5.0\wwwroot\" />
  <ContentRoot BasePath="/" Path="C:\Repos\newbe\Newbe.BookmarkManager\src\Newbe.BookmarkManager\obj\Debug\net5.0\scopedcss\bundle\" />
</StaticWebAssets>
```

The first part of this ``BasePath="_content/AntDesign"` is the location of the static file for a razor class libary.

So, we need to copy these files to the `wwwroot/_content/AntDesign` folder in the build task.

Tip: `_content` is not a reserved folder, so you can use this path without renaming it.

**Comment by mingyaulee** [comment]
Does this work with another file path without the characted '_'? Chrome refuses to load extensions with a directory name prefix _

**Comment by newbe36524** [comment]
Unfortunately it doesn't work, so rename it and remove the prefix  _

**Comment by mingyaulee** [comment]
@newbe36524 please try with v0.1.7, it should be copying the static web assets from the packages references now.

**Comment by newbe36524** [comment]
Thanks to you wonderful job, it works very well in my project with v0.1.7!
Please feel free to close this issue as you want.

**Comment by mingyaulee** [comment]
Awesome! Thanks for the confirmation.
