### ISSUE TITLE
  How to use HttpClient to access B website from A website across the domain ?

### ISSUE THREAD

**Issue by Ponderfly** [mingyaulee/Blazor.BrowserExtension#51]
Error message: Access to fetch at 'B' from origin 'A' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I currently use the 'CORS Unblock' extension to access

**Comment by mingyaulee** [comment]
This is more of a Blazor specific feature, maybe you can try out [this configuration](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.http.webassemblyhttprequestmessageextensions.setbrowserrequestmode?view=aspnetcore-5.0) for sending with NoCors mode.

**Comment by Ponderfly** [comment]
using var msg = new HttpRequestMessage();
        msg .SetBrowserRequestMode(BrowserRequestMode.NoCors);
        msg .Method = HttpMethod.Get;
        msg .RequestUri = new Uri("https://www.B.com");
        using var response = await Http.SendAsync(msg );
        var text = await response.Content.ReadAsStringAsync();

Now there are no more errors but no response results

**Comment by mingyaulee** [comment]
You can check in the developer tools networks tab, see if the response is returned from the server or is there still cors error in the console.

**Comment by Ponderfly** [comment]
No cors error , no response , if I run in the B site will be able to return the response results

**Comment by Ponderfly** [comment]
In ask a question using the code to get a cookie reported an error
"var cookie = await WebExtensions.Cookies.GetAllCookieStores();"

Error: Target object is null or undefined.
    at JsBindNet._invokeFunctionInternal (JsBindNet.js:957:15)
    at JsBindNet.InvokeFunctionAsync (JsBindNet.js:877:32)
    at blazor.webassembly.js:1:3337
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (blazor.webassembly.js:1:62747)
    at Object.mono_wasm_invoke_js_blazor (dotnet.7.0.2.tt5z2s8frk.js:5983:44)
    at _mono_wasm_invoke_js_blazor (dotnet.7.0.2.tt5z2s8frk.js:9832:103886)
    at dotnet.wasm:0x1d4d8
    at dotnet.wasm:0x1c906

**Comment by mingyaulee** [comment]
It would be good if you can share a minimal reproducible sample to see what is happening. From what you have described, it seems like even with simple JavaScript it will not work as well, if this is the case it will not be related to Blazor.

For the cookies API make sure you have included the permission in the manifest and if you're calling from content script, check if the API is something that is not available in content script.

**Comment by Ponderfly** [comment]
Thanks, I am using it in content_scripts, but the cross-domain is accessible only in Background,
