### ISSUE TITLE
WebExtensions cannot be used in the content script

### ISSUE THREAD

**Issue by wf-soft** [mingyaulee/Blazor.BrowserExtension#53]
I tried to open a new page in the content script
```
    string indexPageUrl = null;
    private async Task OpenIndex()
    {
        indexPageUrl = await WebExtensions.Runtime.GetURL("index.html");
        await WebExtensions.Tabs.Create(new WebExtensions.Net.Tabs.CreateProperties() { Url = indexPageUrl });
    }
```

The following script will throw an exception. How should I open a new page in the content script

```
    _invokeFunctionInternal(invokeFunctionOption) {
      const targetObject = JsObjectHandler.getObjectFromAccessPath(invokeFunctionOption.accessPath);
      if (targetObject === undefined || targetObject === null) {
        throw new Error("Target object is null or undefined.");
      }
```
![image](https://user-images.githubusercontent.com/62228539/215411801-6fc6caba-3232-4083-b943-725f48d7490c.png)

**Comment by mingyaulee** [comment]
Content scripts have very limited permission, in order to do that, you will have to send messages to the background worker unfortunately.

**Comment by wf-soft** [comment]
@mingyaulee Message needs to extend the ID, but I use (await WebExtensions. Management GetSelf ()). The ID will also throw an exception

**Comment by mingyaulee** [comment]
No, there is no need to get the ID. Just use the `runtime.sendMessage` API or any other method suggested from [here](https://developer.chrome.com/docs/extensions/mv3/messaging/).

**Comment by wf-soft** [comment]
@mingyaulee Thank you. Problem solved.

**Comment by taylorchasewhite** [comment]
I love this package/library, so thank you for creating it. One question I have is that I'd like to _use_ sendMessage to invoke a web request, but ideally, using my C# client services that use `HttpClient`. The way I can imagine doing this is:

1. `sendMessage` from content script.
2. BackgroundWorker.js receives the message, and invokes a .NET service call (??? how!!!)
3. Sends the response from the .NET call to the content script.

Are there any examples of (or does the BackgroundWorker have access to) invoking .NET calls (using [JsInvokable](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-7.0)).

**Comment by NilkOne** [comment]
Hello @taylorchasewhite , I d'ont understand how to use sendMessage from js to .NET ?
In my js content script, I would like to invoke .NET function like this

DotNet.invokeMethodAsync('MyNamespace', 'UpdateCardData', index, {
        price,
        title,
        location,
        link
    })
but that doesn't work becoup DotNet is undefined

**Comment by mingyaulee** [comment]
`sendMessage` API is for [messaging within the extension](https://developer.chrome.com/docs/extensions/develop/concepts/messaging). Calling .Net from JS can be achieved using `DotNet` object like you mentioned, but it has to be called after the application is initialized. You can hook into the `afterStarted` [lifecycle event from `app.js`](https://mingyaulee.github.io/Blazor.BrowserExtension/app-js) to be sure that `DotNet` is available.
