### ISSUE TITLE
How does one add a page to a Chrome side panel?

### ISSUE THREAD

**Issue by squideyes** [mingyaulee/Blazor.BrowserExtension#55]
Hi!  I'd like to add a specialized bookmark manager (akin to theurlist.com) to the Chrome Side Panel, but I can't quite figure it out how to do so.  Any help in this regard would be greatly appreciated...

**Comment by mingyaulee** [comment]
First you have to outline the process of showing the side panel, i.e. is it going to show all the time or only when an event happens (the extension action button is clicked/a button in the page is clicked/a certain page is opened/etc.). When you have figured that out, you can create a side panel in the page using content scripts. One of the sample projects shows the sidebar injected from content script.

**Comment by squideyes** [comment]
I think we're not talking about the same thing.  I don't want to inject a Content Script into the current page, I think, but open a page in the Chrome Side Panel.  If you open Chrome and click on the Show Side Panel button (toolbar; upper right) you'll see what I'm talking about.  Sorry for being confusing

**Comment by squideyes** [comment]
Got it!  Thanks for the clarification.

If I come across an update I’ll be sure to send a note your way.

Keep up the good work (it’s much appreciated!)
