### ISSUE TITLE
Is it possible to call blazor code from BacgroundWorker.js?

### ISSUE THREAD

**Issue by caxepok** [mingyaulee/Blazor.BrowserExtension#56]
Header is the question :) how to call .net core from exnetions`s service_worker?

**Comment by mingyaulee** [comment]
Yes it is possible but not really advisable given the short lived nature of the background worker.

One way is to use JSExport attribute as described in [this documentation page] (https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-7.0). You would want to have a clear separation for common codes and background worker specific codes so that they can be loaded without Blazor dependencies.

Another way is to just start Blazor from the background worker, but you'll have to use a few workarounds like creating a fake DOM since blazor is going to manipulate the DOM for rendering.

**Comment by mattgwagner** [comment]
Right now, I'm creating a "worker" tab that loads and does all of the processing so I can use C#/Blazor, but it feels very heavy-handed... not to mention that Chrome has gotten much more aggressive about 'discarding' tabs after a period of time. I haven't tried the `JSExport` method you mentioned, but that might work for my case as well (e.g. an alarm triggers background work/sync, which I'd prefer to write in C# versus Javascript!).

**Comment by mingyaulee** [comment]
Yeah exactly, if your code is small and doesn't require a lot of dependencies to be loaded I would suggest looking into using JSExport. I feel that there is probably a better way to load and execute the binaries rather than compiling to exe as shown in the documentation I linked to earlier.

**Comment by taylorchasewhite** [comment]
Out of curiosity, I'm trying to wrap my head around how this _should_ be done. 

So, say you want to make authenticated requests to a server. I'm imaging the user experience to be somewhat similar to LastPass's plugin:

1. User logs in from the popup window, which retrieves a JWT or bearer token.
2. The user is later on a content page, which needs data from the server we previously logged into. The content page _requests_ via a postMessage to the popup (or background worker, which one here, unsure?), for a particular set of data.
3. The background worker or popup window sends a web request using the bearer token we previously retrieved and gets the data back, and then sends a postMessage. 

Is this the right way to think about it?

**Comment by mikemakos** [comment]
Hi,

I tried to use a static blazor method from BackgroundWorker.js using the JSInvokable attribute but I always get an undefined error.
Can someone point me with some codesnippet of how to get this to work?

**Comment by mingyaulee** [comment]
> Out of curiosity, I'm trying to wrap my head around how this _should_ be done.
> 
> So, say you want to make authenticated requests to a server. I'm imaging the user experience to be somewhat similar to LastPass's plugin:
> 
> 1. User logs in from the popup window, which retrieves a JWT or bearer token.
> 2. The user is later on a content page, which needs data from the server we previously logged into. The content page _requests_ via a postMessage to the popup (or background worker, which one here, unsure?), for a particular set of data.
> 3. The background worker or popup window sends a web request using the bearer token we previously retrieved and gets the data back, and then sends a postMessage.
> 
> Is this the right way to think about it?

I think that is correct. The background worker receives the message and acts as a gateway to forward the request to the server and injects the token into the request at the same time.

**Comment by mingyaulee** [comment]
> Hi,
> 
> I tried to use a static blazor method from BackgroundWorker.js using the JSInvokable attribute but I always get an undefined error. Can someone point me with some codesnippet of how to get this to work?

As mentioned in the previous comments, I would recommend to go with JSExport instead due to the fact that background workers are not allowed to live persistently.

**Comment by taylorchasewhite** [comment]
> > Out of curiosity, I'm trying to wrap my head around how this _should_ be done.
> > So, say you want to make authenticated requests to a server. I'm imaging the user experience to be somewhat similar to LastPass's plugin:
> > 
> > 1. User logs in from the popup window, which retrieves a JWT or bearer token.
> > 2. The user is later on a content page, which needs data from the server we previously logged into. The content page _requests_ via a postMessage to the popup (or background worker, which one here, unsure?), for a particular set of data.
> > 3. The background worker or popup window sends a web request using the bearer token we previously retrieved and gets the data back, and then sends a postMessage.
> > 
> > Is this the right way to think about it?
> 
> I think that is correct. The background worker receives the message and acts as a gateway to forward the request to the server and injects the token into the request at the same time.

Thanks. I ended up getting my app all working. I may start chiming in on answers here, and/or possibly write up additional recommendations/samples, if you’d like.

**Comment by mingyaulee** [comment]
I feel that this is something extremely common and it would be beneficial if it is included in this package. I have yet to find time to start the work on this. If you are able to see how it can be adapted in this project feel free to send in a PR.
