### ISSUE TITLE
Cannot load extension with file or directory name _content. Filenames starting with "_" are reserved for use by the system

### ISSUE THREAD

**Issue by luxzz** [mingyaulee/Blazor.BrowserExtension#58]
when publishing using Blazor.BrowserExtension.Template, an error will occur 

Cannot load extension with file or directory name _content. Filenames starting with "_" are reserved for use by the system

**Comment by IamSanjid** [comment]
Publishing from Visual Studio is kind of broken for now, use the command `dotnet publish -c Release` command make sure the `cwd` is your project folder, it should publish in `bin/Release/.net<Version>/publish` folder.

**Comment by mingyaulee** [comment]
> when publishing using Blazor.BrowserExtension.Template, an error will occur
> 
> Cannot load extension with file or directory name _content. Filenames starting with "_" are reserved for use by the system

As mentioned by @IamSanjid you need to use the `dotnet publish` command and load the extension from the `publish/browserextension` directory.



> Publishing from Visual Studio is kind of broken for now, use the command `dotnet publish -c Release` command make sure the `cwd` is your project folder, it should publish in `bin/Release/.net<Version>/publish` folder. Btw the package doesn't bundle with a CSP compliant [AOT](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#ahead-of-time-aot-compilation) runtime script, meaning if you compile enabling [AOT](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0#ahead-of-time-aot-compilation)(which is enabled by default for publish builds) it will most likely fail to load your dotnet runtime, you should wait until .Net 8 is released or may be try to use one of the preview versions.

You are right, AOT is not supported by this package. I have not tested with .Net 8 preview yet so I can't be sure if Blazor in .Net 8 is now fully CSP compliant.
