### ISSUE TITLE
InjectionResults returning ValueKind instead of Content Script return value

### ISSUE THREAD

**Issue by bradbrowne** [mingyaulee/Blazor.BrowserExtension#59]
Thank you so much for providing this package -- it is really very helpful!

I am trying to get the results from a query of the DOM using a Content Script and I am only getting the following back in my Injection Results:

```
{
    "ValueKind": 1
}
```

I have created a simple test to narrow down the issue so that I can resolve it and the JS Content Script I am using below just logs a simple object to the Target and return the object:

```js
(async () => {
    const obj = { text: "TEST" };
    console.debug(obj);
    return obj;
})();
```

The C# Injection is below and I am expecting to get the JSON object above, but all I get is `{ "ValueKind": 1 }` as a result:

```csharp
ScriptInjection injection = new ScriptInjection();
var target = new InjectionTarget();
IEnumerable<string> files = new List<string>();

files = files.Concat(new[] { "js/info/get-info.js" });
target.TabId = _tabId;

injection.Files = files;
injection.Target = target;

var injectionResults = await WebExtensions.Scripting.ExecuteScript(injection);
Log.Debug("injectionResults: {@injectionResults}", injectionResults);
var first = injectionResults.FirstOrDefault();
Log.Debug("first: {@first}", first);
var result = first?.Result;
Log.Debug("result: {@result}", result);
```

Below is screenshot of the browser console on the Extension that is logging the results of the injection:

![image](https://user-images.githubusercontent.com/79854/232948049-b4899321-c265-4aba-a932-81e6d2f8d610.png)

And also below is a screenshot of the Target browser tab that the Content Script is being run on:

![image](https://user-images.githubusercontent.com/79854/232948398-4f1561ed-19df-4bc8-8cf8-ccbe5edaaf78.png)

From the above it seems like the Content Script is running successfully, but the Injection Result is not being deserialized properly when it is received.

Is there something additional required to get the return result of the Content Script?

**Comment by mingyaulee** [comment]
What you get back in return is most likely a JsonElement, which you can use to access the properties of dynamic objects with the indexer or you can deserialize it into a proper class that matches the data of the object returned.

**Comment by bradbrowne** [comment]
@mingyaulee thank you, I was able to get the return result of the Content Script using the following code:

```csharp
// deserialize result json to array of string 
var resultStringArray = JsonConvert.DeserializeObject<string[]>(result.ToString())!; 
Log.Debug("resultStringArray: {@resultStringArray}", resultStringArray);
```
