### ISSUE TITLE
how to establish  connection,is there any examples?

### ISSUE THREAD

**Issue by hanxiao123** [mingyaulee/Blazor.BrowserExtension#60]
I need to send message at popup.html，but it 's error.
Could not establish connection. Receiving end does not exist.

could I receive it at Background.razor like this?

` protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        await WebExtensions.Runtime.OnMessage.AddListener(HandMsg);
    }
`

**Comment by mingyaulee** [comment]
Unfortunately this is a limitation of the manifest v3 because background workers are short lived, all the listeners have to be registered synchronously in the js file. That is why the listeners created from Blazor are ignored because they are registered too late.
