### ISSUE TITLE
Receiving Message from BackgroundWorker

### ISSUE THREAD

**Issue by taylorchasewhite** [mingyaulee/Blazor.BrowserExtension#61]
I'm a bit at a loss for how to _receive_ data inside a ContentScript component after _sending_ a message.

For instance, say I've got a component rendered on a page that triggers a message to the BackgroundWorker.js:

```
	private async Task GetHoursData()
	{
		GetHoursRequest request = new(dateRange!);
		JsonElement jsonElement = await WebExtensions.Runtime.SendMessage(null, request, null);
		string response = jsonElement.GetRawText();
		_hoursStringResponse = response;
		_hours = DeserializeHours(response);
	}

	private class GetHoursRequest
	{
		public GetHoursRequest(DateRange dateRange)
		{
			Start = dateRange.StartDate;
			End = dateRange.EndDate;
		}
		public string Name => "getHours";
		public DateTime Start { get; set; }
		public DateTime End { get; set; }
	}
```

The BackgroundWorker.js handles the message by sending an outgoing web request and returning the response data:
```
browser.runtime.onMessage.addListener(
    async function (request, sender, sendResponse)
    {
        console.log(request);
        console.log(sender.tab ?
            "from a content script:" + sender.tab.url :
            "from the extension");
        if (request.name == "getHours")
        {
            const hoursData = await hours.getOurGovHours(request.start, request.end);

            sendResponse(hoursData);
        }
        else
            sendResponse({farewell: "goodbye"});
    }
);
```

`sendResponse` doesn't seem to work, and if it does, the JsonElement returned from WebExtensions.Runtime.SendMessage isn't populated.

[Chrome also says this](https://developer.chrome.com/docs/extensions/mv3/messaging/) about `sendResponse`:

> For new extensions you should prefer promises over callbacks. If you're using callbacks, the sendResponse() callback is only valid if used synchronously, or if the event handler returns true to indicate that it will respond asynchronously. The sendMessage() function's callback will be invoked automatically if no handlers return true or if the sendResponse() callback is garbage-collected.

My next thought is that I could send a message _from_ the BackgroundWorker.js to the content script, but it's unclear to me how to listen to messages from the components? Is this the right approach, and if so, is there an example of this?

**Comment by taylorchasewhite** [comment]
I figured this out—I’ll reply tomorrow morning and close this with the answer.

**Comment by mingyaulee** [comment]
You are in the right track, since this package used the webextensions polyfill, all calls are converted to asynchronous promises, therefore the sendResponse does not work. The solution is simply to return the response object instead.
