### ISSUE TITLE
About inject code  in OnInitializedAsync does not work

### ISSUE THREAD

**Issue by hanxiao123** [mingyaulee/Blazor.BrowserExtension#64]
Now  I want to inject some js code in ContentScript.razor, it seems not work,
` protected async override Task OnInitializedAsync()
    {
        await JSRuntime.InvokeVoidAsync("eval", @"
            window.myBlazorFunction = function(name) {
                console.log('Hello, ' + name + '!');
            };
        ");
       
        await base.OnInitializedAsync();
    }`
but below code is work fine.
`  await JSRuntime.InvokeVoidAsync("alert", "121");`

**Comment by hanxiao123** [comment]
I note   'unsafe-eval' is disabled in v3.

**Comment by mingyaulee** [comment]
Sorry for the late reply. Yes unsafe-eval is no longer allowed due to tighter security policies. No remote script is allowed to be executed in a web extension.
