### ISSUE TITLE
.NET 8 Support

### ISSUE THREAD

**Issue by johnW-ret** [mingyaulee/Blazor.BrowserExtension#67]
Exception

> MSB4018	The "BlazorToBrowserExtensionProcessStaticWebAssetsManifest" task failed unexpectedly.
> System.IO.FileNotFoundException: Could not find file 'C:\Users\\...\bin\Debug\net8.0\Retruate.Kikai.BrowserExtension.StaticWebAssets.xml'.
> File name: 'C:\Users\\...\bin\Debug\net8.0\Retruate.Kikai.BrowserExtension.StaticWebAssets.xml'
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
>    at System.IO.StreamReader..ctor(String path)
>    at Blazor.BrowserExtension.Build.Tasks.StaticWebAssets.XmlManifestProcessor.ReadFromFile(String filePath)
>    at Blazor.BrowserExtension.Build.Tasks.BlazorToBrowserExtensionProcessStaticWebAssetsManifest.Process(String filePath, IEnumerable`1 excludePaths, String outputPath)
>    at Blazor.BrowserExtension.Build.Tasks.BlazorToBrowserExtensionProcessStaticWebAssetsManifest.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Retruate.Kikai.BrowserExtension	C:\Users\user\.nuget\packages\blazor.browserextension.build\0.10.7\build\Blazor.BrowserExtension.Build.targets	286	

is resolved by
> [Blazor.BrowserExtension.Build.targets](https://github.com/mingyaulee/Blazor.BrowserExtension/blob/6ff5c6dc346095d75d348b6889d44a2dd45dfae1/src/Blazor.BrowserExtension.Build/build/Blazor.BrowserExtension.Build.targets)
```diff
-<_BrowserExtension_Project_BuildOutput_StaticWebAssets_Manifest_FilePath Condition="('$(TargetFramework)' == 'net6.0' OR '$(TargetFramework)' == 'net7.0' OR '$(TargetFramework)' == 'net8.0') AND Exists('$(TargetDir)$(ProjectName).staticwebassets.runtime.json')">$(TargetDir)$(ProjectName).staticwebassets.runtime.json</_BrowserExtension_Project_BuildOutput_StaticWebAssets_Manifest_FilePath>
+<_BrowserExtension_Project_BuildOutput_StaticWebAssets_Manifest_FilePath Condition="('$(TargetFramework)' == 'net6.0' OR '$(TargetFramework)' == 'net7.0') AND Exists('$(TargetDir)$(ProjectName).staticwebassets.runtime.json')">$(TargetDir)$(ProjectName).staticwebassets.runtime.json</_BrowserExtension_Project_BuildOutput_StaticWebAssets_Manifest_FilePath>

```
but I see some TODO comments for .NET 8 so I thought it's worth opening an issue before making a PR for a single line of code.

**Comment by mingyaulee** [comment]
Yes indeed there are some things to do for .Net 8, I am planning to drop support for .Net 5 and remove the custom runtime.js for .Net 8.

I haven't had the time to tinker with .Net 8 yet but you can try to update this line, if it works then you can create a PR for it.

**Comment by mingyaulee** [comment]
.Net 8 RC support is now added in [v0.12.0](https://github.com/mingyaulee/Blazor.BrowserExtension/releases/tag/v0.12.0)
