### ISSUE TITLE
When renaming or moving a project, the wrong file may be copied if the obj folder is not deleted.

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#7]
1. create the project tpl1
2. install the appropriate packages and initialize the project
3. rename the project folder to tpl2
4. try to build, it will report an error
5. delete obj bin
6. build, success.

Similarly, if the entire project is copied directly, there are problems

1. create the project tpl1
2. install the appropriate packages and initialize the project
3. copy the whole project folder and rename it as tpl2
4. try to build, no error is reported, but actually the file contents are copied from tpl1
5. delete obj bin
6. build, success.

**Comment by mingyaulee** [comment]
This will be fixed in the next release, where only the static web assets XML matching the project name will be processed.

**Comment by newbe36524** [comment]
Nice.

**Comment by mingyaulee** [comment]
Fixed with v0.1.12
