### ISSUE TITLE
Not able to read local file in WASM .NET Core layer  

### ISSUE THREAD

**Issue by geetamshukla** [mingyaulee/Blazor.BrowserExtension#73]
Hi @mingyaulee  

I have developed a chrome extension using WASM and able to set bidirectional communication meaning I am able to call .NET Core function from JavaScript lib   and JavaScript functions from WASM Dlls  . 

Now , I have a file URL which I want to download and then read the content in .NET Core layer .  I have tried multiple ways but unable to achieve it in Blazor.BrowserExtension .

I am able to download a file in user's download folder and want to read the file from there not sure how we can achieve it as whatever file location I hardcode and pass it to WASM Dlls it always gives null as location . 

Even Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);   always give Null  though I have path available in registry 

@mingyaulee  can u suggest a way by which we can read a file from file system  ?

**Comment by mingyaulee** [comment]
In web extensions development, there is no access to the file system for security purposes. Web extensions have a lot less permissions and mostly are limited to only functionalities within the browser.

**Comment by geetamshukla** [comment]
> In web extensions development, there is no access to the file system for security purposes. Web extensions have a lot less permissions and mostly are limited to only functionalities within the browser.

I get that directly the file system access is not available is there any other way to achieve the same ??

**Comment by mingyaulee** [comment]
Unfortunately in the [API list](https://developer.chrome.com/docs/extensions/reference/) there's none for extensions. There is a very limited functionality provided by the [HTML5 File API](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications) which you can check out to see if it suits your need.
