### ISSUE TITLE
Errors and questions when it is published from visual studio

### ISSUE THREAD

**Issue by mikemakos** [mingyaulee/Blazor.BrowserExtension#74]
Hi,

I have some questions regarding the build process of the blazor.

1. When I build in release mode from Visual studio, all work fine, but when I click the publish button, and I load the extension in Chrome, I get the below errors:

![image](https://github.com/mingyaulee/Blazor.BrowserExtension/assets/72599583/8ebe6bc1-2f63-4a75-be11-34f71f26d616)

How can I resolve this?

2. Can we use the AOT compilation? I have tried it but I get the error:
![image](https://github.com/mingyaulee/Blazor.BrowserExtension/assets/72599583/949f5324-2c84-4753-981a-049def40bf9b)

3. During the build in release mode the dlls are included along with the .dll.gz files, and from what I can see the dll files are used instead of the dll.gz, I have not overriden any configuration such as BrowserExtensionEnableCompression.

**Comment by mingyaulee** [comment]
Hi there,
1. Are you experiencing the issue with .Net 7 or .Net 8?
2. No there is no support for AOT here yet.
3. For browser extensions the gzip is always ignored, all the files are local and we do not have a server to download the files from, therefore gzip cannot be supported, unless of course if you can implement gzip decompression in JavaScript.

**Comment by mingyaulee** [comment]
Closed due to inactivity. Please reopen if the issue still persists.
