### ISSUE TITLE
Delete *.dll in Release configuration and keep only *.br

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/Blazor.BrowserExtension#8]
This helps reduce the size of the extensions package by at least 75%

more details: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#compression

**Comment by mingyaulee** [comment]
Please correct me if I'm wrong, I think the compression support for static hosting needs to be manually fetched and decoded in the JavaScript and not out of the box from Blazor's build process. So if you are using compression then you need to add a postbuild execution to delete the .dll files for your project. If the deletion is done from this package, the standard projects does not have brotli output and loading out of the box, which will cause the application to not load.

**Comment by newbe36524** [comment]
1. Now brotli output will be generated normally. So the output directory will have *.dll as well as *.gz or *.br, and actually at runtime, if we add the scripts described in the doc, we can do without the *.dll files, removing them will help to reduce the package size. 
2. I am curious if it is possible to do the "remove *.dll" and append "decode.js" steps automatically for this project under release configuration.

**Comment by mingyaulee** [comment]
I guess it is possible, but with .Net 5 I am not seeing brotli files from project build, it is just `.dll` and `.gz`. Are you using .Net 6 and is it generating brotli files from project build?

**Comment by newbe36524** [comment]
You should run 'publish' to create that files
```bash
dotnet publish -o out -c Release
```

**Comment by mingyaulee** [comment]
Yeah I think this is a good one to work on. I'll look into supporting publish soon.

**Comment by mingyaulee** [comment]
This has been added in v0.2.1

**Comment by newbe36524** [comment]
Thanks to your hard work, it work very well as I tested. But a small BUG.
https://github.com/mingyaulee/Blazor.BrowserExtension/issues/11
