### ISSUE TITLE
Pass variable from BackgroundWorker.js to Popup.razor

### ISSUE THREAD

**Issue by JackkFi5h** [mingyaulee/Blazor.BrowserExtension#84]
I've been struggling to pass a variable (URL of active tab) from backgroundworker.js to the popup.razor page that I want to use for my plugin. I have tried JSInterop to no success as well as calling DotNet.invokeMethodAsync in the background worker but that also doesn't work.

Any way to achieve this or even another way of accessing the currently active tab in blazor? 

Thanks

**Comment by mingyaulee** [comment]
As far as I know, you can use [`runtime.sendMessage`](https://developer.chrome.com/docs/extensions/reference/api/runtime#method-sendMessage) from popup and listen to messages from the background worker through `runtime.onMessage` event.

**Comment by JackkFi5h** [comment]
Hi, Thanks for getting back so quickly,

This allows me to pass value from popup to backgroundworker, but I need it to work the other way round, as I am only able to get the activeTab within backgroundworker.js if that makese sense?

Any ideas? I feel this is close!

Thanks

**Comment by JackkFi5h** [comment]
Update, I found on the mozilla docs a reference to a sendRepsonse parameter that can achieve what I need! Thanks for your help @mingyaulee :)

`browser.runtime.onMessage.addListener((data, sender, sendResponse) => {
    console.log("onmessage called", data);
    sendResponse({ response: "hello" }, 1000);
    return true;
});`

**Comment by mingyaulee** [comment]
No worries, good to hear you got it!
