### ISSUE TITLE
Use the .Net browser extension Apis in a zero UI plugin

### ISSUE THREAD

**Issue by sodiqyekeen** [mingyaulee/Blazor.BrowserExtension#85]
I want to use this package mainly because of the extension APIs available in C#. However, I can't seem to find an entry point into my C# code without loading a page.
For example, I want to add an event listener for the onclick of the action and also register some other listeners from the onistalled event handler.

**Comment by mingyaulee** [comment]
In this case I am assuming that you are writing these event handlers in background worker JS. This [page](https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-8.0) might help you get started with interop to WASM from JS and you can then use the WebExtensions.Net library to interop with the extensions API without Blazor. It's a lot of work to be done, but it looks like it's achievable.

**Comment by sodiqyekeen** [comment]
Thank you for getting back to me so quickly. I am considering using Blazor because I would still have some modals displayed from the plugin. Just that I want to invoke .Net from JS when the plugin is loaded (onistalled). Anyways, I will check the documentation.

**Comment by mingyaulee** [comment]
In the background worker, Blazor is not loaded at all, therefore it would need to be initialized separately but the initialization is very heavy and depends on DOM which is not available in background worker. Currently the only way to use C# in background worker is to initialize the dotnet wasm separately just like how Blazor initializes it.

**Comment by sodiqyekeen** [comment]
I am not able to create dotnet instance from the service worker. Getting this error:
`MONO_WASM: import() is disallowed on ServiceWorkerGlobalScope by the HTML specification.`

**Comment by mingyaulee** [comment]
Dynamic import is not allowed but static import should be allowed in the background worker. You can try to move the import to the top, does that work or is the error coming from the `dotnet.js` file?

**Comment by mingyaulee** [comment]
In that case, unfortunately it is a lot harder to use WASM in background worker unless the Chrome extensions team allow dynamic import or dotnet team creates a js file with static imports.

**Comment by LostBeard** [comment]
dynamic imports in the service worker not being supported does make it a lot harder. It does not seem like they intend on enabling it any time soon. 

> import() is disallowed on ServiceWorkerGlobalScope by the HTML specification.See https://github.com/w3c/ServiceWorker/issues/1356.

I wrote code to modify the Blazor framework javascript files post-build so that they use importScripts when in a workerscope, and document.createElement('script') ... when in a window. Working in a Crhome extension service worker, workers, etc. 👍👍

**Comment by mingyaulee** [comment]
Using C# in background is now supported with the version [v1.5.0](https://github.com/mingyaulee/Blazor.BrowserExtension/releases/tag/v1.5.0).
