### ISSUE TITLE
Error in invoke.js

### ISSUE THREAD

**Issue by LeonSnajdr** [mingyaulee/Blazor.BrowserExtension#90]
I am trying to create an extension in dotnet8 with the version 1.1.0. But after building the extension, I get an error:
![image](https://github.com/mingyaulee/Blazor.BrowserExtension/assets/94352142/8187bc6a-47de-4995-ac81-67d26401935d)

I have followed this YouTube tutorial: https://www.youtube.com/watch?v=oyH3G_ntpKk.
In the comments, some other developer mentioned the same issue 
![image](https://github.com/mingyaulee/Blazor.BrowserExtension/assets/94352142/cce1d01e-a4a5-4c73-be4e-aad8cbc53c0f)

The last version, that is working for me is the 0.10.7, but I cant use it because its dotnet7

**Comment by mingyaulee** [comment]
Thank you for raising this! I have fixed it in v1.1.3 and marked the previous versions as deprecated in NuGet.
